name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django
        pip install djangorestframework
        pip install django-cors-headers
        #pip install coveralls
        #pip install pytest pytest-cov coveralls coverage
        pip install -U coverage coveralls
        #pip install coveralls==3.3.1 coverage==7.2.7
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}



        
    - name: Run Tests
      run: |
        #cd app; python manage.py test api_rest
        #coverage run --branch app/manage.py test api_rest
        coverage run --source=app/api_rest --branch app/manage.py test api_rest
        #ls -a
        coverage xml
        ls -a
        coveralls --service=github
        #cd app; python manage.py runserver
        #pytest --cov=app/api_rest app/api_rest/tests
      
        
